name: cuy_flutter_dev
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  flutter_bloc: ^8.1.4

  dartz: ^0.10.1

  equatable: ^2.0.5

  get_it: ^7.6.7

  intl: ^0.18.1

  retrofit: ^4.1.0

  dio: ^5.4.1

  shared_preferences: ^2.2.2
  
  google_fonts: ^6.2.1

  font_awesome_flutter: ^10.7.0
  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  retrofit_generator: ^8.1.0

  build_runner: ^2.4.8

  mockito: ^5.4.4

  http_mock_adapter: ^0.6.1

  bloc_test: ^9.1.2

flutter:

  uses-material-design: true

  generate: true
